apiVersion: apps/v1
kind: Deployment
metadata:
  name: calendar
spec:
  replicas: {{ .Values.calendar.replicaCount }}
  selector:
    matchLabels:
      app: calendar
  template:
    metadata:
      labels:
        app: calendar
    spec:
      containers:
        - name: app
          image: {{ .Values.calendar.image }}
          ports:
            - containerPort: 8080
            - containerPort: 7070