apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  ports:
    - port: {{ .Values.rabbitmq.port }}
      targetPort: {{ .Values.rabbitmq.port }}
      protocol: TCP
      name: rabbitmq
  selector:
    app: rabbitmq