apiVersion: apps/v1
kind: Deployment
metadata:
  name: sender
spec:
  replicas: {{ .Values.sender.replicaCount }}
  selector:
    matchLabels:
      app: sender
  template:
    metadata:
      labels:
        app: sender
    spec:
      containers:
        - name: app
          image: {{ .Values.sender.image }}