storage = "sql"

[logger]
level = "INFO"

[db]
host = "postgres"
port = 5432
user = "root"
password = "root"
name = "app_db"

[rabbit]
host = "rabbitmq"
port = 5672
user = "guest"
password = "guest"
exchange = "app"
queue = "calendar"

[scheduler]
update = "5s"
remove = "1m"